import assert from "node:assert/strict";
import path from "node:path";
import test from "node:test";

import {
  GENERATED_MARKER,
  hasGeneratedMarker,
  isGeneratedBundlePath,
  isSupportedSourcePath,
  makeOutputPath
} from "../src/output";

test("derives a .bundle.luau output name from Lua and Luau entries", () => {
  assert.equal(makeOutputPath(path.join("scripts", "main.luau")), path.join("scripts", "main.bundle.luau"));
  assert.equal(makeOutputPath(path.join("scripts", "main.lua")), path.join("scripts", "main.bundle.luau"));
});

test("recognizes supported sources and generated bundles case-insensitively", () => {
  assert.equal(isSupportedSourcePath("main.LUAU"), true);
  assert.equal(isSupportedSourcePath("main.txt"), false);
  assert.equal(isGeneratedBundlePath("main.BUNDLE.LUAU"), true);
  assert.equal(isGeneratedBundlePath("main.luau"), false);
});

test("accepts current and legacy generated markers near the file header", () => {
  assert.equal(hasGeneratedMarker(`--!nocheck\n${GENERATED_MARKER}\n`), true);
  assert.equal(
    hasGeneratedMarker(
      "--!nocheck\n-- Generated by luau-single-file-bundler. DO NOT EDIT.\n"
    ),
    true
  );
  assert.equal(hasGeneratedMarker("-- generated by something else\n"), false);
  assert.equal(hasGeneratedMarker(`${"x".repeat(1100)}${GENERATED_MARKER}`), false);
});

test("rejects output naming for unsupported entry extensions", () => {
  assert.throws(() => makeOutputPath("main.txt"), /\.lua or \.luau/);
});
