import path from "node:path";

import * as vscode from "vscode";

import { BundleError, compileBundle } from "./compiler";
import { VscodeFileHost } from "./fileHost";
import {
  isGeneratedBundlePath,
  isSupportedSourcePath,
  makeOutputPath
} from "./output";
import { outputConflict } from "./policies";
import { RemoteController } from "./remote";
import { RemoteSidebar } from "./sidebar";

const COMMAND_ID = "ezLuauUtility.compileActiveFile";
const DIAGNOSTIC_SOURCE = "ez-luau-utility";

export function activate(context: vscode.ExtensionContext): void {
  const diagnostics = vscode.languages.createDiagnosticCollection("ez-luau-utility");
  const remote = new RemoteController(context);
  const sidebar = new RemoteSidebar(remote);

  context.subscriptions.push(
    diagnostics,
    remote,
    sidebar,
    ...remote.registerCommands(),
    vscode.commands.registerCommand(COMMAND_ID, () =>
      compileActiveFile(diagnostics, remote)
    ),
    vscode.workspace.onDidChangeTextDocument((event) => {
      diagnostics.delete(event.document.uri);
    })
  );
}

export function deactivate(): void {}

async function compileActiveFile(
  diagnostics: vscode.DiagnosticCollection,
  remote: RemoteController
): Promise<void> {
  diagnostics.clear();

  const editor = vscode.window.activeTextEditor;
  if (editor === undefined || editor.document.uri.scheme !== "file") {
    await vscode.window.showErrorMessage(
      "ez-luau-utility needs an active saved .lua or .luau file."
    );
    return;
  }

  const entryUri = editor.document.uri;
  const entryPath = entryUri.fsPath;
  if (!isSupportedSourcePath(entryPath)) {
    await vscode.window.showErrorMessage(
      "ez-luau-utility only compiles .lua and .luau files."
    );
    return;
  }

  if (isGeneratedBundlePath(entryPath)) {
    await vscode.window.showErrorMessage(
      "Generated .bundle.luau files cannot be compiled as entry files."
    );
    return;
  }

  const workspaceFolder = vscode.workspace.getWorkspaceFolder(entryUri);
  if (workspaceFolder === undefined || workspaceFolder.uri.scheme !== "file") {
    await vscode.window.showErrorMessage(
      "The active file must belong to a local or remote filesystem workspace folder."
    );
    return;
  }

  const outputPath = makeOutputPath(entryPath);
  const outputUri = vscode.Uri.file(outputPath);
  const outputDocument = vscode.workspace.textDocuments.find(
    (document) =>
      document.uri.scheme === "file" && samePath(document.uri.fsPath, outputPath)
  );

  const dirtyConflict = outputConflict({
    exists: false,
    isDirty: outputDocument?.isDirty === true
  });
  if (dirtyConflict === "dirty-buffer") {
    await vscode.window.showErrorMessage(
      `Cannot overwrite ${path.basename(outputPath)} because it has unsaved changes.`
    );
    return;
  }

  if (await uriExists(outputUri)) {
    let currentOutput: string;
    try {
      const bytes = await vscode.workspace.fs.readFile(outputUri);
      currentOutput = new TextDecoder("utf-8", { fatal: true }).decode(bytes);
    } catch (error) {
      await vscode.window.showErrorMessage(
        `Cannot read the existing bundle: ${errorMessage(error)}`
      );
      return;
    }

    if (
      outputConflict({ exists: true, isDirty: false, contents: currentOutput }) ===
      "unowned-file"
    ) {
      await vscode.window.showErrorMessage(
        `Refusing to overwrite ${path.basename(outputPath)} because it was not generated by ez-luau-utility.`
      );
      return;
    }
  }

  const host = new VscodeFileHost(workspaceFolder.uri.fsPath);

  try {
    const result = await compileBundle(entryPath, host);
    await vscode.workspace.fs.writeFile(outputUri, new TextEncoder().encode(result.code));

    const moduleLabel = result.dependencies.length === 1 ? "module" : "modules";
    const choice = await vscode.window.showInformationMessage(
      `Compiled ${result.dependencies.length} ${moduleLabel} to ${path.basename(outputPath)}.`,
      "Open Bundle",
      "Upload Bundle"
    );

    if (choice === "Open Bundle") {
      const document = await vscode.workspace.openTextDocument(outputUri);
      await vscode.window.showTextDocument(document, { preview: false });
    } else if (choice === "Upload Bundle") {
      await remote.uploadContent(result.code, path.basename(outputPath));
    }
  } catch (error) {
    if (error instanceof BundleError) {
      await reportBundleError(error, host, diagnostics);
      return;
    }

    await vscode.window.showErrorMessage(`Luau bundling failed: ${errorMessage(error)}`);
  }
}

async function reportBundleError(
  error: BundleError,
  host: VscodeFileHost,
  diagnostics: vscode.DiagnosticCollection
): Promise<void> {
  let contents = "";
  try {
    contents = await host.readText(error.filePath);
  } catch {
    // A zero-length fallback range is still useful for read failures.
  }

  const uri = await host.uriFor(error.filePath);
  const range = new vscode.Range(
    positionAt(contents, error.start),
    positionAt(contents, Math.min(contents.length, error.end))
  );
  const diagnostic = new vscode.Diagnostic(
    range,
    error.message,
    vscode.DiagnosticSeverity.Error
  );
  diagnostic.code = error.code;
  diagnostic.source = DIAGNOSTIC_SOURCE;
  diagnostics.set(uri, [diagnostic]);

  await vscode.window.showErrorMessage(error.message, "Show Problem").then(async (choice) => {
    if (choice !== "Show Problem") {
      return;
    }

    const document = await vscode.workspace.openTextDocument(uri);
    const editor = await vscode.window.showTextDocument(document);
    editor.selection = new vscode.Selection(range.start, range.end);
    editor.revealRange(range, vscode.TextEditorRevealType.InCenterIfOutsideViewport);
  });
}

function positionAt(contents: string, offset: number): vscode.Position {
  const target = Math.max(0, Math.min(contents.length, offset));
  let line = 0;
  let lineStart = 0;

  for (let index = 0; index < target; index += 1) {
    const character = contents[index];
    if (character === "\n") {
      line += 1;
      lineStart = index + 1;
    }
  }

  return new vscode.Position(line, target - lineStart);
}

async function uriExists(uri: vscode.Uri): Promise<boolean> {
  try {
    await vscode.workspace.fs.stat(uri);
    return true;
  } catch {
    return false;
  }
}

function samePath(left: string, right: string): boolean {
  const normalizedLeft = path.normalize(left);
  const normalizedRight = path.normalize(right);
  return process.platform === "win32"
    ? normalizedLeft.toLowerCase() === normalizedRight.toLowerCase()
    : normalizedLeft === normalizedRight;
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
