import path from "node:path";

export const GENERATED_MARKER =
  "-- Generated by ez-luau-utility. DO NOT EDIT.";

const LEGACY_GENERATED_MARKER =
  "-- Generated by luau-single-file-bundler. DO NOT EDIT.";

const SOURCE_EXTENSION = /\.(?:lua|luau)$/i;
const BUNDLE_EXTENSION = /\.bundle\.luau$/i;

export function isSupportedSourcePath(filePath: string): boolean {
  return SOURCE_EXTENSION.test(filePath);
}

export function isGeneratedBundlePath(filePath: string): boolean {
  return BUNDLE_EXTENSION.test(filePath);
}

export function makeOutputPath(entryPath: string): string {
  if (!isSupportedSourcePath(entryPath)) {
    throw new Error("The entry file must use the .lua or .luau extension.");
  }

  return entryPath.replace(SOURCE_EXTENSION, ".bundle.luau");
}

export function hasGeneratedMarker(contents: string): boolean {
  const header = contents.slice(0, 1024);
  return (
    header.includes(GENERATED_MARKER) ||
    header.includes(LEGACY_GENERATED_MARKER)
  );
}

export function displayPath(workspaceRoot: string, filePath: string): string {
  const relative = path.relative(workspaceRoot, filePath);
  return (relative || path.basename(filePath)).split(path.sep).join("/");
}
